### ISSUE TITLE
cmake build failed

### ISSUE THREAD

**Issue by amnox** [freudi74/gradle-cmake-plugin#3]
Any idea why this is happening, I am using the default config provided in the readme

> Task :cmakeBuild FAILED
Caching disabled for task ':cmakeBuild' because:
  Caching has not been enabled for the task
Task ':cmakeBuild' is not up-to-date because:
  Task has not declared any outputs despite executing actions.
  CMakePlugin.task cmakeBuild - exec: cmake --build . --config Release --target install 
  CMakePlugin.cmakeConfigure - ERRORS: 
make: *** No rule to make target 'install'.  Stop.

**Comment by freudi74** [comment]
I assume you use the line: 
`buildTarget='install'`
in your gradle script, and your CMakeLists.txt has no install configured. If you just leave that line out, there should be no error. Please confirm so that I can close this.

**Comment by amnox** [comment]
Thanks for the help, this fixed it. This issue can be closed now. Unrelated to this can you tell me how to use the C++ files that were built using CMAKE, through java's  system.loadlibrary . Thanks for the reply!
